### ISSUE TITLE
PayloadCrypter

### ISSUE THREAD

**Issue by MeanMachine123** [EvilBytecode/GolangStyle#1]
**Payload Crypter is giving issue.......How can I resolve ???**

go run main.go    
# github.com/EvilBytecode/GolangStyle/pkg
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:14:33: undefined: syscall.NewLazyDLL
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:82:20: undefined: syscall.Handle
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:167:22: undefined: syscall.NewLazyDLL

Urgent Plz....

**Comment by EvilBytecode** [comment]
this is just the package problems you can remove it @MeanMachine123 .
